# Site settings
title: Lambdaspace
email: info@lambdaspace.gr
description: >
    Join a vibrant community of hackers
baseurl: "https://bacharakis.github.io/githubpages-boilerplate"
url: "https://bacharakis.github.io/githubpages-boilerplate"
twitter_username: lambdaspace
github_username:  lambdaspace

# Build settings
markdown: kramdown

include: ['_pages']
