# Site settings
title: Lambdaspace
email: info@lambdaspace.gr
description: >
    Join a vibrant community of hackers
baseurl: ""
url: "https://lambdaspace.gr"
twitter_username: lambdaspace
github_username:  lambdaspace

# Build settings
markdown: kramdown

include: ['_pages']
